# Generated by Django 5.1.3 on 2024-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_set',
            field=models.BooleanField(default=False),
        ),
    ]
